run:
	gcc -c -O2 art!ld.c	
	gcc -c -O2 extras!ld.c 
	gcc -c -O2 file!ld.c 
	gcc -c -O2 games!ld.c 
	gcc -c -O2 nina!ld.c
	gcc -c -O2 osmanip!ld.c
	gcc -c -O2 path!ld.c 
	gcc -c -O2 style!ld.c 
	gcc -c -O2 sys!ld.c
	gcc -shared -o LD_LIB.dll *.o
	move /Y LD_LIB.dll ..
